name: Release

on:
  push:
    # poor man's publication with multiple packages
    tags:
      - "openai-v*.*.*"
    branches:
      - main

permissions:
  contents: read

jobs:
  openai-packages:
    permissions:
      attestations: write
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    env:
      PROJECT_DIR: instrumentation/elastic-opentelemetry-instrumentation-openai/
    steps:
      - uses: actions/checkout@v4

      - run: pip install build==1.2.1
        working-directory: ${{ env.PROJECT_DIR }}

      - run: python -m build
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Upload Packages
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            '${{ env.PROJECT_DIR }}/dist/*.whl'
            '${{ env.PROJECT_DIR }}/dist/*tar.gz'

  openai-publish-pypi:
    needs:
      - openai-packages
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: packages
          path: instrumentation/elastic-opentelemetry-instrumentation-openai/dist

      - name: Upload pypi.org
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@8a08d616893759ef8e1aa1f2785787c0b97e20d6
        with:
          repository-url: https://upload.pypi.org/legacy/
          attestation: true
